const arr=new Array()
console.log(arr)
console.log(typeof arr)
const arr2=new Array(1,2,3,4,5,6)
console.log(arr2)
console.log(arr2[0])
console.log(arr2[2])
arr2.push(8)
console.log(arr2)
console.log(arr2.pop())