let obj=new Date()
let obj2=new Date("3-6-2024")
let obj3=new Date("4,7,2022")
let obj4=new Date("6/7/2022")
console.log(obj)
console.log(obj.toString())
console.log(obj.getDate())
console.log(obj.getDay())
console.log(obj.getYear())
console.log(obj.getFullYear())
console.log(obj.getMonth()+1)
console.log(obj.getTime())
console.log(obj.getHours())
console.log(obj.getMinutes())
console.log(obj.getSeconds())
console.log(obj.getMilliseconds())
// obj2.setDate("3-6-2024")
// console.log(obj3)
// console.log(obj2)
console.log(obj2.getDate())
console.log(obj3.getDate())
console.log(obj4.getDate())
console.log(obj3.getDay())
console.log(obj4.getDay())