console.log(document.querySelector(".box").innerHTML)
// console.log(document.querySelector(".box")
// [0].innerHTML)--> throw an error.
console.log(document.querySelectorAll(".box")[0].innerHTML)
console.log(document.querySelectorAll(".box")[1].innerHTML)
console.log(document.querySelectorAll(".box")[2].innerHTML)
console.log(document.querySelectorAll(".box")[3].innerHTML)
console.log(document.querySelector(".container").innerHTML)
console.log(document.querySelector(".box").innerText)
console.log(document.querySelectorAll(".box")[0].innerText)
console.log(document.querySelectorAll(".box")[1].innerText)
console.log(document.querySelectorAll(".box")[2].innerText)
console.log(document.querySelectorAll(".box")[3].innerText)
console.log(document.querySelector(".container").innerText)
console.log(document.querySelector(".container").outerHTML)
console.log(document.querySelector(".box").outerHTML)
console.log(document.querySelectorAll(".box")[0].outerHTML)
console.log(document.querySelectorAll(".box")[1].outerHTML)
console.log(document.querySelectorAll(".box")[2].outerHTML)
console.log(document.querySelectorAll(".box")[3].outerHTML)
console.log("harshit")
console.log(document.querySelector(".container").tagName)
console.log(document.querySelector(".box").tagName)
console.log(document.querySelector(".container").nodeName)
console.log(document.querySelector(".box").nodeName)
console.log(document.querySelector(".container").textContent)
console.log(document.querySelector(".box").textContent)
console.log(document.querySelectorAll(".box")[0].textContent)
console.log(document.querySelectorAll(".box")[1].textContent)
console.log(document.querySelectorAll(".box")[2].textContent)
console.log(document.querySelectorAll(".box")[3].textContent)
console.log(document.querySelector(".container").hidden)
console.log(document.querySelector(".container").hidden=true)
// changing of innerHTML of a class:
// before changing:
console.log(`before changing innerHTML:  ${document.querySelector(".box").innerHTML}`)
// after changing:
console.log(`after changing innerHTML:  ${document.querySelector(".box").innerHTML="Hey,I am Harshit"}`)
// changing of innerText of a class:
// before changing:
console.log(`before changing innerText: ${document.querySelector(".box").innerText}`)
// after changing:
console.log(`after changing innerText:  ${document.querySelector(".box").innerText="Hey,I am Harsha"}`)
console.log(`is first ".box" class has "style" attribute:  ${document.querySelector(".box").hasAttribute('style')}`)
// or
console.log(`is first ".box" class has "style" attribute:  ${document.querySelectorAll(".box")[0].hasAttribute('style')}`)
console.log(`is second ".box" class has "style" attribute: ${document.querySelectorAll(".box")[1].hasAttribute('style')}`)
console.log(`the first ".box" class "style" attribute innerText is: ${document.querySelector(".box").getAttribute('style')}`)
console.log(`the first ".box" class "style" attribute innerText before changing is: ${document.querySelector(".box").getAttribute('style')}`)
document.querySelector(".box").setAttribute('style','height:30px,width:50px,border:2px solid black')
console.log(`the first ".box" class "style" attribute innerText after changing is: ${document.querySelector(".box").getAttribute('style')}`)
console.log("the all attributes of first '.box' class are:")
console.log(document.querySelector(".box").attributes)
