// let obj=new Math
console.log(Math)
console.log(typeof Math)
console.log(Math.ceil(4.6))
console.log(Math.floor(4.6))
console.log(Math.round(4.6))
console.log(Math.round(4.4))
console.log(Math.abs(-4.4))
console.log(Math.abs(4.4))
console.log(Math.max(4,5,7,9))
console.log(Math.min(4,5,7,9))
console.log(Math.random()*10)
console.log(Math.pow(2,4))
console.log(Math.sqrt(4))